# Generated by Django 4.0.1 on 2022-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='u',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('account_user_serial_key', models.TextField(null=True)),
                ('account_server_origin', models.TextField()),
                ('logged_in', models.BooleanField(null=True)),
            ],
        ),
    ]
