# Generated by Django 4.0.1 on 2022-05-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.UUIDField(auto_created=True),
        ),
    ]
