# Generated by Django 4.0.1 on 2022-05-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_session_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='logged_out',
            field=models.BooleanField(null=True),
        ),
    ]
