# Generated by Django 4.0.1 on 2022-06-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_session_logged_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session',
            new_name='session_id',
        ),
    ]
