# Generated by Django 4.0.1 on 2022-11-21 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent_folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.TextField()),
                ('folder_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='web.u')),
            ],
        ),
        migrations.CreateModel(
            name='folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.TextField()),
                ('folder_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to='web.u')),
                ('in_parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_folder', to='file_storage.parent_folder')),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('file_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='web.u')),
                ('in_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='file_storage.folder')),
                ('in_parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='par_folder', to='file_storage.parent_folder')),
            ],
        ),
    ]
