# Generated by Django 4.0.1 on 2022-03-26 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_device_variables_value_type_and_more'),
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='web.u'),
        ),
        migrations.CreateModel(
            name='parent_folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.TextField()),
                ('folder_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='web.u')),
            ],
        ),
        migrations.CreateModel(
            name='folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.TextField()),
                ('folder_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to='web.u')),
                ('in_parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_folder', to='file_storage.parent_folder')),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='in_parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='par_folder', to='file_storage.parent_folder'),
        ),
        migrations.AlterField(
            model_name='files',
            name='in_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='file_storage.folder'),
        ),
    ]
