# Generated by Django 4.0.1 on 2022-02-14 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField()),
                ('device_name', models.TextField()),
                ('ip_address', models.GenericIPAddressField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='u',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('account_server_origin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='device_variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.TextField()),
                ('value', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('from_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='web.device')),
            ],
        ),
        migrations.CreateModel(
            name='device_statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.TextField()),
                ('for_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev', to='web.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_account', to='web.u'),
        ),
        migrations.CreateModel(
            name='current_device_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='web.device_statuses')),
                ('for_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='web.device')),
            ],
        ),
    ]
