# Generated by Django 4.0.1 on 2022-02-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_u_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='u',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
