# Generated by Django 4.0.1 on 2022-02-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_u_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_variables',
            name='value_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='device_variables',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
