# Generated by Django 3.0.8 on 2021-11-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_hash',
            field=models.TextField(null=True),
        ),
    ]
