# Generated by Django 3.0.8 on 2021-12-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20211217_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('LIS', 'light')], max_length=5, null=True),
        ),
    ]
